version: '3.8'

services:
  contextqa-chat-history:
    image: redis:7.0.11-alpine
    container_name: contextqa-chat-history
    restart: unless-stopped
    ports:
      - 6378:6379
    volumes:
      - redis:/data
    networks:
      - contextqa
  contextqa-server:
    build: ./api
    container_name: contextqa-server
    restart: unless-stopped
    volumes:
      - $VECTOR_STORE_HOME:/var/embeddings
      - ./api:/app/
    ports:
      - 8081:8080
    env_file:
      - ./contextqa.env
    environment:
      - DEPLOYMENT=dev
      - REDIS_URL=redis://contextqa-chat-history:6379/0
    entrypoint: uvicorn contextqa.main:app --host 0.0.0.0 --port 8080 --reload --log-level debug
    networks:
      - contextqa
    depends_on:
      - contextqa-chat-history
  contextqa-client:
    build: ./client
    container_name: contextqa-client
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./client:/app/
      - /app/dist # avoids to replacement of this directory
    depends_on:
      - contextqa-server
    entrypoint: npm run serve
    networks:
      - contextqa
networks:
  contextqa:
volumes:
  redis:
    driver: local
