version: '3.8'

services:
  contextqa-chat-history-dev:
    image: redis:7.0.11-alpine
    container_name: contextqa-chat-history-dev
    restart: unless-stopped
    ports:
      - 6378:6379
    volumes:
      - redis-dev:/data
    networks:
      - contextqa-dev
  contextqa-server-dev:
    build: ./api
    container_name: contextqa-server-dev
    restart: unless-stopped
    volumes:
      - $VECTOR_STORE_HOME:/var/embeddings
      - ./api:/app/
    ports:
      - 8081:8080
    env_file:
      - ./contextqa.env
    environment:
      - DEPLOYMENT=dev
      - REDIS_URL=redis://contextqa-chat-history-dev:6379/0
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080 --reload --log-level debug
    networks:
      - contextqa-dev
    depends_on:
      - contextqa-chat-history-dev
  contextqa-client-dev:
    build: ./client
    container_name: contextqa-client-dev
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./client:/app/
      - /app/dist # avoids to replacement of this directory
    depends_on:
      - contextqa-server-dev
    entrypoint: npm run serve
    networks:
      - contextqa-dev
networks:
  contextqa-dev:
volumes:
  redis-dev:
    driver: local
