"""unique index name

Revision ID: 3058bf204a05
Revises: b7d862d599fe
Create Date: 2024-05-16 00:25:23.549287

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3058bf204a05"
down_revision: Union[str, None] = "b7d862d599fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("index", schema=None) as batch_op:
        batch_op.create_unique_constraint("index_unique", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("index", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
